from pathlib import Path
import re, json, html
ROOT = Path(__file__).resolve().parents[2]
keys = 'loadingTitle loadingBody directBody approvalBody requestAction approvalFooter sendingBody sendingAction joiningBody joiningAction sentTitle sentBody done viewRequests pendingTitle pendingBody errorSendTitle errorLoadTitle errorJoinTitle errorCancelTitle errorBody unavailableTitle unavailableBody fullTitle fullBody close cancelling'.split()
rows = {
'en': 'Loading group|Preparing your invitation.|You can join directly and start chatting.|An admin must approve your request to join.|Request access|You can enter the chat once you are accepted.|Sending your request.|Sending…|Preparing to join the group.|Joining…|Request sent|An admin will review your request. The group will appear in your conversations once you are accepted.|Got it|View requests|Pending approval|Your request is still pending. You can view or cancel it at any time.|Could not send|Could not load|Could not join|Could not cancel|Check your connection and try again.|Link unavailable|This link is no longer active. Ask a group admin for a new one.|Group is full|This group has reached its member limit. Try again later.|Close|Cancelling…',
'es': 'Cargando grupo|Estamos preparando la invitación.|Puedes unirte directamente y empezar a conversar.|Un admin debe aprobar tu entrada al grupo.|Solicitar acceso|Podrás entrar al chat cuando te acepten.|Estamos enviando tu solicitud.|Enviando…|Estamos preparando tu entrada al grupo.|Entrando…|Solicitud enviada|Un admin revisará tu solicitud. El grupo aparecerá en tus conversaciones cuando te acepten.|Entendido|Ver solicitudes|Pendiente de aprobación|Tu solicitud sigue pendiente. Puedes consultarla o cancelarla cuando quieras.|No se ha podido enviar|No se ha podido cargar|No se ha podido entrar|No se ha podido cancelar|Comprueba tu conexión e inténtalo de nuevo.|Enlace no disponible|Este enlace ya no está activo. Pide uno nuevo a un admin del grupo.|El grupo está completo|Este grupo ha alcanzado el límite de miembros. Inténtalo más adelante.|Cerrar|Cancelando…',
'ca': 'Carregant el grup|Estem preparant la invitació.|Pots unir-te directament i començar a conversar.|Un admin ha d’aprovar la teva entrada al grup.|Sol·licitar accés|Podràs entrar al xat quan t’acceptin.|Estem enviant la teva sol·licitud.|Enviant…|Estem preparant la teva entrada al grup.|Entrant…|Sol·licitud enviada|Un admin revisarà la teva sol·licitud. El grup apareixerà a les teves converses quan t’acceptin.|Entesos|Veure sol·licituds|Pendent d’aprovació|La teva sol·licitud continua pendent. Pots consultar-la o cancel·lar-la quan vulguis.|No s’ha pogut enviar|No s’ha pogut carregar|No s’ha pogut entrar|No s’ha pogut cancel·lar|Comprova la connexió i torna-ho a provar.|Enllaç no disponible|Aquest enllaç ja no està actiu. Demana’n un de nou a un admin del grup.|El grup és ple|Aquest grup ha arribat al límit de membres. Torna-ho a provar més endavant.|Tancar|Cancel·lant…',
'fr': 'Chargement du groupe|Nous préparons votre invitation.|Vous pouvez rejoindre directement le groupe et commencer à discuter.|Un admin doit approuver votre entrée dans le groupe.|Demander à rejoindre|Vous pourrez accéder à la discussion après votre acceptation.|Envoi de votre demande.|Envoi…|Préparation de votre entrée dans le groupe.|Connexion…|Demande envoyée|Un admin examinera votre demande. Le groupe apparaîtra dans vos conversations après votre acceptation.|Compris|Voir les demandes|En attente d’approbation|Votre demande est toujours en attente. Vous pouvez la consulter ou l’annuler à tout moment.|Échec de l’envoi|Chargement impossible|Impossible de rejoindre|Annulation impossible|Vérifiez votre connexion et réessayez.|Lien indisponible|Ce lien n’est plus actif. Demandez-en un nouveau à un admin du groupe.|Le groupe est complet|Ce groupe a atteint sa limite de membres. Réessayez plus tard.|Fermer|Annulation…',
'de': 'Gruppe wird geladen|Deine Einladung wird vorbereitet.|Du kannst direkt beitreten und chatten.|Ein Admin muss deinen Beitritt genehmigen.|Beitritt anfragen|Nach der Annahme kannst du den Chat öffnen.|Deine Anfrage wird gesendet.|Wird gesendet…|Dein Gruppenbeitritt wird vorbereitet.|Beitritt läuft…|Anfrage gesendet|Ein Admin prüft deine Anfrage. Die Gruppe erscheint nach der Annahme in deinen Unterhaltungen.|Verstanden|Anfragen ansehen|Wartet auf Genehmigung|Deine Anfrage ist noch offen. Du kannst sie jederzeit ansehen oder zurückziehen.|Senden fehlgeschlagen|Laden fehlgeschlagen|Beitritt fehlgeschlagen|Zurückziehen fehlgeschlagen|Prüfe deine Verbindung und versuche es erneut.|Link nicht verfügbar|Dieser Link ist nicht mehr aktiv. Bitte einen Gruppenadmin um einen neuen.|Gruppe ist voll|Diese Gruppe hat ihre Mitgliedergrenze erreicht. Versuche es später erneut.|Schließen|Wird zurückgezogen…',
'it': 'Caricamento del gruppo|Stiamo preparando il tuo invito.|Puoi unirti direttamente e iniziare a chattare.|Un admin deve approvare il tuo ingresso nel gruppo.|Richiedi accesso|Potrai accedere alla chat quando verrai accettato.|Stiamo inviando la tua richiesta.|Invio…|Stiamo preparando il tuo ingresso nel gruppo.|Accesso…|Richiesta inviata|Un admin esaminerà la tua richiesta. Il gruppo apparirà nelle tue conversazioni quando verrai accettato.|Ho capito|Vedi richieste|In attesa di approvazione|La tua richiesta è ancora in attesa. Puoi consultarla o annullarla quando vuoi.|Invio non riuscito|Caricamento non riuscito|Accesso non riuscito|Annullamento non riuscito|Controlla la connessione e riprova.|Link non disponibile|Questo link non è più attivo. Chiedine uno nuovo a un admin del gruppo.|Il gruppo è al completo|Questo gruppo ha raggiunto il limite di membri. Riprova più tardi.|Chiudi|Annullamento…',
'pt-BR': 'Carregando grupo|Estamos preparando seu convite.|Você pode entrar diretamente e começar a conversar.|Um admin precisa aprovar sua entrada no grupo.|Solicitar acesso|Você poderá entrar no chat quando for aceito.|Estamos enviando sua solicitação.|Enviando…|Estamos preparando sua entrada no grupo.|Entrando…|Solicitação enviada|Um admin analisará sua solicitação. O grupo aparecerá nas suas conversas quando você for aceito.|Entendi|Ver solicitações|Aguardando aprovação|Sua solicitação ainda está pendente. Você pode consultá-la ou cancelá-la quando quiser.|Não foi possível enviar|Não foi possível carregar|Não foi possível entrar|Não foi possível cancelar|Verifique sua conexão e tente novamente.|Link indisponível|Este link não está mais ativo. Peça um novo a um admin do grupo.|O grupo está cheio|Este grupo atingiu o limite de membros. Tente novamente mais tarde.|Fechar|Cancelando…',
'pt-PT': 'A carregar grupo|Estamos a preparar o teu convite.|Podes entrar diretamente e começar a conversar.|Um admin tem de aprovar a tua entrada no grupo.|Pedir acesso|Poderás entrar no chat quando fores aceite.|Estamos a enviar o teu pedido.|A enviar…|Estamos a preparar a tua entrada no grupo.|A entrar…|Pedido enviado|Um admin irá analisar o teu pedido. O grupo aparecerá nas tuas conversas quando fores aceite.|Entendido|Ver pedidos|A aguardar aprovação|O teu pedido continua pendente. Podes consultá-lo ou cancelá-lo quando quiseres.|Não foi possível enviar|Não foi possível carregar|Não foi possível entrar|Não foi possível cancelar|Verifica a tua ligação e tenta novamente.|Ligação indisponível|Esta ligação já não está ativa. Pede uma nova a um admin do grupo.|O grupo está cheio|Este grupo atingiu o limite de membros. Tenta novamente mais tarde.|Fechar|A cancelar…',
'nl': 'Groep laden|Je uitnodiging wordt voorbereid.|Je kunt direct deelnemen en beginnen met chatten.|Een beheerder moet je deelname goedkeuren.|Toegang aanvragen|Je kunt de chat openen zodra je bent toegelaten.|Je verzoek wordt verzonden.|Verzenden…|Je deelname wordt voorbereid.|Deelnemen…|Verzoek verzonden|Een beheerder beoordeelt je verzoek. De groep verschijnt in je gesprekken zodra je bent toegelaten.|Begrepen|Verzoeken bekijken|Wacht op goedkeuring|Je verzoek staat nog open. Je kunt het op elk moment bekijken of annuleren.|Verzenden mislukt|Laden mislukt|Deelnemen mislukt|Annuleren mislukt|Controleer je verbinding en probeer het opnieuw.|Link niet beschikbaar|Deze link is niet meer actief. Vraag een groepsbeheerder om een nieuwe.|Groep is vol|Deze groep heeft het maximale aantal leden bereikt. Probeer het later opnieuw.|Sluiten|Annuleren…',
'pl': 'Wczytywanie grupy|Przygotowujemy Twoje zaproszenie.|Możesz dołączyć od razu i zacząć rozmawiać.|Administrator musi zatwierdzić Twoje dołączenie do grupy.|Poproś o dostęp|Uzyskasz dostęp do czatu po zatwierdzeniu.|Wysyłamy Twoją prośbę.|Wysyłanie…|Przygotowujemy Twoje dołączenie do grupy.|Dołączanie…|Prośba wysłana|Administrator rozpatrzy Twoją prośbę. Grupa pojawi się w Twoich rozmowach po zatwierdzeniu.|Rozumiem|Zobacz prośby|Oczekuje na zatwierdzenie|Twoja prośba nadal oczekuje. Możesz ją sprawdzić lub anulować w dowolnej chwili.|Nie udało się wysłać|Nie udało się wczytać|Nie udało się dołączyć|Nie udało się anulować|Sprawdź połączenie i spróbuj ponownie.|Link niedostępny|Ten link nie jest już aktywny. Poproś administratora grupy o nowy.|Grupa jest pełna|Ta grupa osiągnęła limit członków. Spróbuj ponownie później.|Zamknij|Anulowanie…',
'ja': 'グループを読み込み中|招待を準備しています。|そのまま参加して会話を始められます。|参加には管理者の承認が必要です。|参加を申請|承認されるとチャットに参加できます。|申請を送信しています。|送信中…|グループへの参加を準備しています。|参加中…|申請を送信しました|管理者が申請を確認します。承認されるとグループが会話一覧に表示されます。|了解|申請を見る|承認待ち|申請はまだ承認待ちです。いつでも確認や取り消しができます。|送信できませんでした|読み込めませんでした|参加できませんでした|取り消せませんでした|接続を確認して再試行してください。|リンクを利用できません|このリンクは無効です。グループの管理者に新しいリンクを依頼してください。|グループは満員です|このグループはメンバー数の上限に達しています。後でもう一度お試しください。|閉じる|取り消し中…',
'ko': '그룹 불러오는 중|초대를 준비하고 있습니다.|바로 참여하고 대화를 시작할 수 있습니다.|관리자가 그룹 참여를 승인해야 합니다.|참여 요청|승인되면 채팅에 참여할 수 있습니다.|요청을 보내고 있습니다.|보내는 중…|그룹 참여를 준비하고 있습니다.|참여 중…|요청을 보냈습니다|관리자가 요청을 검토합니다. 승인되면 그룹이 대화 목록에 표시됩니다.|확인|요청 보기|승인 대기 중|아직 승인 대기 중입니다. 언제든 요청을 확인하거나 취소할 수 있습니다.|보내지 못했습니다|불러오지 못했습니다|참여하지 못했습니다|취소하지 못했습니다|연결을 확인하고 다시 시도하세요.|링크를 사용할 수 없습니다|이 링크는 더 이상 유효하지 않습니다. 그룹 관리자에게 새 링크를 요청하세요.|그룹 정원이 찼습니다|그룹이 최대 인원에 도달했습니다. 나중에 다시 시도하세요.|닫기|취소 중…',
'zh-Hant': '正在載入群組|正在準備邀請。|你可以直接加入並開始聊天。|管理員必須核准你加入群組。|申請加入|獲得核准後即可進入聊天。|正在傳送你的申請。|傳送中…|正在準備加入群組。|加入中…|申請已傳送|管理員將審核你的申請。獲得核准後，群組會出現在你的對話列表中。|知道了|查看申請|等待核准|你的申請仍在等待核准。你可以隨時查看或取消。|無法傳送|無法載入|無法加入|無法取消|請檢查連線後重試。|連結無法使用|此連結已失效。請向群組管理員索取新連結。|群組已滿|此群組已達成員人數上限。請稍後再試。|關閉|取消中…',
'hi': 'समूह लोड हो रहा है|आपका आमंत्रण तैयार कर रहे हैं।|आप सीधे शामिल होकर बातचीत शुरू कर सकते हैं।|समूह में शामिल होने के लिए एडमिन की स्वीकृति ज़रूरी है।|प्रवेश का अनुरोध करें|स्वीकृति मिलने पर आप चैट में प्रवेश कर सकेंगे।|आपका अनुरोध भेज रहे हैं।|भेज रहे हैं…|समूह में आपका प्रवेश तैयार कर रहे हैं।|शामिल हो रहे हैं…|अनुरोध भेज दिया गया|एडमिन आपके अनुरोध की समीक्षा करेगा। स्वीकृति मिलने पर समूह आपकी बातचीत में दिखाई देगा।|समझ गया|अनुरोध देखें|स्वीकृति की प्रतीक्षा में|आपका अनुरोध अभी लंबित है। आप इसे कभी भी देख या रद्द कर सकते हैं।|भेजा नहीं जा सका|लोड नहीं हो सका|शामिल नहीं हो सके|रद्द नहीं हो सका|अपना कनेक्शन जाँचें और फिर से कोशिश करें।|लिंक उपलब्ध नहीं है|यह लिंक अब सक्रिय नहीं है। समूह के एडमिन से नया लिंक माँगें।|समूह भर गया है|इस समूह में सदस्यों की सीमा पूरी हो गई है। बाद में फिर कोशिश करें।|बंद करें|रद्द कर रहे हैं…',
'id': 'Memuat grup|Sedang menyiapkan undangan Anda.|Anda dapat langsung bergabung dan mulai mengobrol.|Admin harus menyetujui Anda untuk bergabung.|Minta akses|Anda dapat masuk ke chat setelah diterima.|Sedang mengirim permintaan Anda.|Mengirim…|Sedang menyiapkan Anda untuk bergabung.|Bergabung…|Permintaan terkirim|Admin akan meninjau permintaan Anda. Grup akan muncul di percakapan Anda setelah diterima.|Mengerti|Lihat permintaan|Menunggu persetujuan|Permintaan Anda masih tertunda. Anda dapat melihat atau membatalkannya kapan saja.|Gagal mengirim|Gagal memuat|Gagal bergabung|Gagal membatalkan|Periksa koneksi Anda dan coba lagi.|Tautan tidak tersedia|Tautan ini tidak lagi aktif. Minta tautan baru dari admin grup.|Grup penuh|Grup ini telah mencapai batas anggota. Coba lagi nanti.|Tutup|Membatalkan…',
 'tr': 'Grup yükleniyor|Davetin hazırlanıyor.|Doğrudan katılıp sohbete başlayabilirsin.|Gruba katılmanı bir yönetici onaylamalı.|Katılma isteği gönder|Kabul edildiğinde sohbete girebilirsin.|İsteğin gönderiliyor.|Gönderiliyor…|Gruba katılımın hazırlanıyor.|Katılınıyor…|İstek gönderildi|Bir yönetici isteğini inceleyecek. Kabul edildiğinde grup konuşmalarında görünecek.|Anladım|İstekleri gör|Onay bekliyor|İsteğin hâlâ bekliyor. İstediğin zaman görüntüleyebilir veya iptal edebilirsin.|Gönderilemedi|Yüklenemedi|Katılınamadı|İptal edilemedi|Bağlantını kontrol edip tekrar dene.|Bağlantı kullanılamıyor|Bu bağlantı artık etkin değil. Bir grup yöneticisinden yeni bağlantı iste.|Grup dolu|Bu grup üye sınırına ulaştı. Daha sonra tekrar dene.|Kapat|İptal ediliyor…',
}
qual={'en':'values','id':'values-in','pt-BR':'values-b+pt+BR','pt-PT':'values-b+pt+PT','zh-Hant':'values-b+zh+Hant'}
def resource(key): return 'groups_sheet_'+re.sub(r'(?<!^)(?=[A-Z])','_',key).lower()
for lang,row in rows.items():
    values=row.split('|')
    if len(values)!=len(keys): raise ValueError((lang,len(values)))
    ios=ROOT/'Moments/Moments'/f'{lang}.lproj/Localizable.strings'
    text=ios.read_text()
    android=ROOT/'MomentsAndroid/app/src/main/res'/qual.get(lang,'values-'+lang)/'strings_groups.xml'
    xml=android.read_text()
    for key,value in zip(keys,values):
        text=re.sub(r'^"groups\.sheet\.'+re.escape(key)+r'" = .*;\n?', '', text, flags=re.M)
        text+='"groups.sheet.'+key+'" = '+json.dumps(value,ensure_ascii=False)+';\n'
        res=resource(key)
        xml=re.sub(r'\s*<string name="'+res+r'">.*?</string>', '', xml)
        escaped=html.escape(value,quote=False).replace("'", "\\'").replace('"','\\"')
        xml=xml.replace('</resources>',f'    <string name="{res}">{escaped}</string>\n</resources>')
    ios.write_text(text);android.write_text(xml)
p=ROOT/'MomentsAndroid/app/src/main/java/com/moments/android/views/messaging/groups/GroupStrings.kt'
s=p.read_text()
for key in keys:
    if f'"sheet.{key}" ->' not in s: s=s.replace('    else ->',f'    "sheet.{key}" -> R.string.{resource(key)}\n    else ->')
p.write_text(s)
print(f'{len(keys)} texts synced in {len(rows)} locales for both apps.')
