from pathlib import Path
import json, re, html

# Shared group-chat copy for iOS and Android. Run from any directory.
ROOT = Path(__file__).resolve().parents[2]
keys = ['title', 'empty', 'emptyBody', 'memberCount', 'create', 'name', 'pickerHint', 'selectedCount', 'noConnections', 'add', 'search', 'details', 'privacy', 'older', 'reply', 'photo', 'message', 'cancel', 'send', 'save', 'mute', 'members', 'owner', 'admin', 'promote', 'demote', 'remove', 'manage', 'leave', 'leaveBody', 'removeBody', 'errorTitle', 'ok', 'back', 'error', 'unavailable', 'keyError', 'sendError', 'photoError', 'manageError', 'notification', 'invitations', 'accept', 'decline', 'invited', 'pendingInvitations']
translations = {
  "en": "Groups|No groups yet|Create a group to share with your people.|%d members|New group|Group name|Choose people on Moments. Invite at least 2 to create a group, with up to 50 members in total.|%d selected|No people found.|Invite people|Search people|Group details|Messages are end-to-end encrypted. People who accept an invitation can read the group history.|Earlier messages|Reply|Photo|Message|Cancel|Send|Save|Mute notifications|Members|Owner|Admin|Make admin|Remove admin role|Remove member|Manage member|Leave group|You will lose access to the group. If you are the owner, ownership will pass to another member.|This person will lose access to the group. Previously downloaded messages cannot be erased from their device.|Could not complete the action|OK|Back|Could not load the group. Go back and try again.|You no longer have access to this group.|Chat keys are unavailable. Members need to set up or restore their chat keys.|Could not send. Your draft is still here; try again.|Could not load this photo.|Could not update the group. Check your connection and permissions, then try again.|%@ sent a message|Group invitations|Accept|Decline|Invitation sent|Pending invitations",
  "es": "Grupos|Todavía no tienes grupos|Crea un grupo para compartir con los tuyos.|%d miembros|Nuevo grupo|Nombre del grupo|Elige personas de Moments. Invita al menos a 2 para crear un grupo, con hasta 50 miembros en total.|%d seleccionados|No se han encontrado personas.|Invitar personas|Buscar personas|Detalles del grupo|Los mensajes están cifrados de extremo a extremo. Quienes acepten la invitación podrán leer el historial del grupo.|Mensajes anteriores|Responder|Foto|Mensaje|Cancelar|Enviar|Guardar|Silenciar notificaciones|Miembros|Propietario|Admin|Hacer admin|Quitar rol de admin|Expulsar miembro|Gestionar miembro|Salir del grupo|Perderás acceso al grupo. Si eres su propietario, otra persona asumirá ese rol.|Esta persona perderá acceso al grupo. Los mensajes ya descargados no se pueden borrar de su dispositivo.|No se ha podido completar la acción|Aceptar|Atrás|No se ha podido cargar el grupo. Vuelve atrás e inténtalo de nuevo.|Ya no tienes acceso a este grupo.|Las claves del chat no están disponibles. Los miembros deben configurar o restaurar sus claves del chat.|No se ha podido enviar. Tu borrador sigue aquí; inténtalo de nuevo.|No se ha podido cargar esta foto.|No se ha podido actualizar el grupo. Comprueba tu conexión y permisos e inténtalo de nuevo.|%@ ha enviado un mensaje|Invitaciones a grupos|Aceptar|Rechazar|Invitación enviada|Invitaciones pendientes",
  "ca": "Grups|Encara no tens grups|Crea un grup per compartir amb els teus.|%d membres|Grup nou|Nom del grup|Tria persones de Moments. Convida’n almenys 2 per crear un grup, amb un màxim de 50 membres.|%d seleccionats|No s’han trobat persones.|Convidar persones|Cercar persones|Detalls del grup|Els missatges estan xifrats d’extrem a extrem. Qui accepti la invitació podrà llegir l’historial del grup.|Missatges anteriors|Respon|Foto|Missatge|Cancel·la|Envia|Desa|Silencia les notificacions|Membres|Propietari|Admin|Fes admin|Treu el rol d’admin|Expulsa el membre|Gestiona el membre|Surt del grup|Perdràs l’accés al grup. Si n’ets el propietari, una altra persona assumirà aquest rol.|Aquesta persona perdrà l’accés al grup. No es poden esborrar del seu dispositiu els missatges ja descarregats.|No s’ha pogut completar l’acció|D’acord|Enrere|No s’ha pogut carregar el grup. Torna enrere i prova-ho de nou.|Ja no tens accés a aquest grup.|Les claus del xat no estan disponibles. Els membres han de configurar o restaurar les seves claus.|No s’ha pogut enviar. L’esborrany continua aquí; torna-ho a provar.|No s’ha pogut carregar aquesta foto.|No s’ha pogut actualitzar el grup. Comprova la connexió i els permisos i torna-ho a provar.|%@ ha enviat un missatge|Invitacions a grups|Acceptar|Rebutjar|Invitació enviada|Invitacions pendents",
  "de": "Gruppen|Noch keine Gruppen|Erstelle eine Gruppe, um dich mit deinen Leuten auszutauschen.|%d Mitglieder|Neue Gruppe|Gruppenname|Wähle Personen auf Moments. Lade mindestens 2 ein, um eine Gruppe mit bis zu 50 Mitgliedern zu erstellen.|%d ausgewählt|Keine Personen gefunden.|Personen einladen|Personen suchen|Gruppendetails|Nachrichten sind Ende-zu-Ende-verschlüsselt. Wer eine Einladung annimmt, kann den Gruppenverlauf lesen.|Ältere Nachrichten|Antworten|Foto|Nachricht|Abbrechen|Senden|Speichern|Benachrichtigungen stummschalten|Mitglieder|Inhaber|Admin|Zum Admin machen|Adminrolle entfernen|Mitglied entfernen|Mitglied verwalten|Gruppe verlassen|Du verlierst den Zugriff auf die Gruppe. Als Inhaber überträgst du diese Rolle an ein anderes Mitglied.|Diese Person verliert den Zugriff auf die Gruppe. Bereits heruntergeladene Nachrichten können nicht von ihrem Gerät gelöscht werden.|Aktion konnte nicht abgeschlossen werden|OK|Zurück|Gruppe konnte nicht geladen werden. Gehe zurück und versuche es erneut.|Du hast keinen Zugriff mehr auf diese Gruppe.|Chatschlüssel sind nicht verfügbar. Mitglieder müssen ihre Chatschlüssel einrichten oder wiederherstellen.|Senden fehlgeschlagen. Dein Entwurf ist noch da; versuche es erneut.|Dieses Foto konnte nicht geladen werden.|Gruppe konnte nicht aktualisiert werden. Prüfe Verbindung und Berechtigungen und versuche es erneut.|%@ hat eine Nachricht gesendet|Gruppeneinladungen|Annehmen|Ablehnen|Einladung gesendet|Ausstehende Einladungen",
  "fr": "Groupes|Aucun groupe pour le moment|Crée un groupe pour échanger avec tes proches.|%d membres|Nouveau groupe|Nom du groupe|Choisissez des personnes sur Moments. Invitez-en au moins 2 pour créer un groupe de 50 membres maximum.|%d sélectionnés|Aucune personne trouvée.|Inviter des personnes|Rechercher des personnes|Détails du groupe|Les messages sont chiffrés de bout en bout. Les personnes qui acceptent une invitation peuvent lire l’historique du groupe.|Messages précédents|Répondre|Photo|Message|Annuler|Envoyer|Enregistrer|Couper les notifications|Membres|Propriétaire|Admin|Nommer admin|Retirer le rôle d’admin|Retirer le membre|Gérer le membre|Quitter le groupe|Tu perdras l’accès au groupe. Si tu en es propriétaire, ce rôle sera transmis à un autre membre.|Cette personne perdra l’accès au groupe. Les messages déjà téléchargés ne peuvent pas être effacés de son appareil.|Impossible de terminer l’action|OK|Retour|Impossible de charger le groupe. Reviens en arrière et réessaie.|Tu n’as plus accès à ce groupe.|Les clés du chat sont indisponibles. Les membres doivent configurer ou restaurer leurs clés.|Envoi impossible. Ton brouillon est toujours là ; réessaie.|Impossible de charger cette photo.|Impossible de mettre à jour le groupe. Vérifie ta connexion et tes autorisations, puis réessaie.|%@ a envoyé un message|Invitations aux groupes|Accepter|Refuser|Invitation envoyée|Invitations en attente",
  "it": "Gruppi|Ancora nessun gruppo|Crea un gruppo per condividere con le persone a te vicine.|%d membri|Nuovo gruppo|Nome del gruppo|Scegli persone su Moments. Invitane almeno 2 per creare un gruppo con un massimo di 50 membri.|%d selezionati|Nessuna persona trovata.|Invita persone|Cerca persone|Dettagli del gruppo|I messaggi sono crittografati end-to-end. Chi accetta un invito può leggere la cronologia del gruppo.|Messaggi precedenti|Rispondi|Foto|Messaggio|Annulla|Invia|Salva|Silenzia notifiche|Membri|Proprietario|Admin|Nomina admin|Rimuovi ruolo di admin|Rimuovi membro|Gestisci membro|Esci dal gruppo|Perderai l’accesso al gruppo. Se sei il proprietario, il ruolo passerà a un altro membro.|Questa persona perderà l’accesso al gruppo. I messaggi già scaricati non possono essere cancellati dal suo dispositivo.|Impossibile completare l’azione|OK|Indietro|Impossibile caricare il gruppo. Torna indietro e riprova.|Non hai più accesso a questo gruppo.|Le chiavi della chat non sono disponibili. I membri devono configurare o ripristinare le proprie chiavi.|Invio non riuscito. La bozza è ancora qui; riprova.|Impossibile caricare questa foto.|Impossibile aggiornare il gruppo. Controlla connessione e permessi, poi riprova.|%@ ha inviato un messaggio|Inviti ai gruppi|Accetta|Rifiuta|Invito inviato|Inviti in attesa",
  "pt-BR": "Grupos|Você ainda não tem grupos|Crie um grupo para compartilhar com quem você gosta.|%d membros|Novo grupo|Nome do grupo|Escolha pessoas no Moments. Convide pelo menos 2 para criar um grupo com até 50 membros.|%d selecionados|Nenhuma pessoa encontrada.|Convidar pessoas|Buscar pessoas|Detalhes do grupo|As mensagens são criptografadas de ponta a ponta. Quem aceitar um convite poderá ler o histórico do grupo.|Mensagens anteriores|Responder|Foto|Mensagem|Cancelar|Enviar|Salvar|Silenciar notificações|Membros|Proprietário|Admin|Tornar admin|Remover função de admin|Remover membro|Gerenciar membro|Sair do grupo|Você perderá o acesso ao grupo. Se for o proprietário, essa função passará para outro membro.|Essa pessoa perderá o acesso ao grupo. Mensagens já baixadas não podem ser apagadas do dispositivo dela.|Não foi possível concluir a ação|OK|Voltar|Não foi possível carregar o grupo. Volte e tente novamente.|Você não tem mais acesso a este grupo.|As chaves do chat estão indisponíveis. Os membros precisam configurar ou restaurar suas chaves.|Não foi possível enviar. Seu rascunho continua aqui; tente novamente.|Não foi possível carregar esta foto.|Não foi possível atualizar o grupo. Verifique sua conexão e permissões e tente novamente.|%@ enviou uma mensagem|Convites para grupos|Aceitar|Recusar|Convite enviado|Convites pendentes",
  "pt-PT": "Grupos|Ainda não tens grupos|Cria um grupo para partilhar com as tuas pessoas.|%d membros|Novo grupo|Nome do grupo|Escolhe pessoas no Moments. Convida pelo menos 2 para criar um grupo com até 50 membros.|%d selecionados|Não foram encontradas pessoas.|Convidar pessoas|Pesquisar pessoas|Detalhes do grupo|As mensagens são encriptadas ponto a ponto. Quem aceitar um convite poderá ler o histórico do grupo.|Mensagens anteriores|Responder|Foto|Mensagem|Cancelar|Enviar|Guardar|Silenciar notificações|Membros|Proprietário|Admin|Tornar admin|Remover função de admin|Remover membro|Gerir membro|Sair do grupo|Perderás o acesso ao grupo. Se fores o proprietário, essa função passará para outro membro.|Esta pessoa perderá o acesso ao grupo. As mensagens já descarregadas não podem ser apagadas do dispositivo dela.|Não foi possível concluir a ação|OK|Voltar|Não foi possível carregar o grupo. Volta atrás e tenta novamente.|Já não tens acesso a este grupo.|As chaves do chat estão indisponíveis. Os membros têm de configurar ou restaurar as suas chaves.|Não foi possível enviar. O teu rascunho continua aqui; tenta novamente.|Não foi possível carregar esta foto.|Não foi possível atualizar o grupo. Verifica a ligação e as permissões e tenta novamente.|%@ enviou uma mensagem|Convites para grupos|Aceitar|Recusar|Convite enviado|Convites pendentes",
  "nl": "Groepen|Nog geen groepen|Maak een groep om te delen met je mensen.|%d leden|Nieuwe groep|Groepsnaam|Kies mensen op Moments. Nodig er minstens 2 uit om een groep met maximaal 50 leden te maken.|%d geselecteerd|Geen mensen gevonden.|Mensen uitnodigen|Mensen zoeken|Groepsdetails|Berichten zijn end-to-end versleuteld. Wie een uitnodiging accepteert, kan de groepsgeschiedenis lezen.|Eerdere berichten|Beantwoorden|Foto|Bericht|Annuleren|Versturen|Opslaan|Meldingen dempen|Leden|Eigenaar|Admin|Admin maken|Adminrol verwijderen|Lid verwijderen|Lid beheren|Groep verlaten|Je verliest toegang tot de groep. Als eigenaar draag je die rol over aan een ander lid.|Deze persoon verliest toegang tot de groep. Al gedownloade berichten kunnen niet van diens apparaat worden gewist.|Actie kon niet worden voltooid|OK|Terug|Groep kon niet worden geladen. Ga terug en probeer het opnieuw.|Je hebt geen toegang meer tot deze groep.|Chatsleutels zijn niet beschikbaar. Leden moeten hun chatsleutels instellen of herstellen.|Versturen mislukt. Je concept is er nog; probeer het opnieuw.|Deze foto kon niet worden geladen.|Groep kon niet worden bijgewerkt. Controleer je verbinding en rechten en probeer het opnieuw.|%@ heeft een bericht verstuurd|Groepsuitnodigingen|Accepteren|Weigeren|Uitnodiging verstuurd|Openstaande uitnodigingen",
  "pl": "Grupy|Nie masz jeszcze grup|Utwórz grupę i dziel się z bliskimi.|Członkowie: %d|Nowa grupa|Nazwa grupy|Wybierz osoby w Moments. Zaproś co najmniej 2, aby utworzyć grupę liczącą do 50 członków.|Wybrano: %d|Nie znaleziono osób.|Zaproś osoby|Szukaj osób|Szczegóły grupy|Wiadomości są szyfrowane od końca do końca. Osoby, które przyjmą zaproszenie, mogą czytać historię grupy.|Wcześniejsze wiadomości|Odpowiedz|Zdjęcie|Wiadomość|Anuluj|Wyślij|Zapisz|Wycisz powiadomienia|Członkowie|Właściciel|Admin|Nadaj rolę admina|Odbierz rolę admina|Usuń członka|Zarządzaj członkiem|Opuść grupę|Stracisz dostęp do grupy. Jeśli jesteś właścicielem, rolę przejmie inny członek.|Ta osoba straci dostęp do grupy. Pobranych wcześniej wiadomości nie można usunąć z jej urządzenia.|Nie udało się wykonać działania|OK|Wstecz|Nie udało się wczytać grupy. Wróć i spróbuj ponownie.|Nie masz już dostępu do tej grupy.|Klucze czatu są niedostępne. Członkowie muszą skonfigurować lub przywrócić swoje klucze.|Nie udało się wysłać. Wersja robocza jest nadal dostępna; spróbuj ponownie.|Nie udało się wczytać tego zdjęcia.|Nie udało się zaktualizować grupy. Sprawdź połączenie i uprawnienia, a następnie spróbuj ponownie.|%@ wysłał(a) wiadomość|Zaproszenia do grup|Przyjmij|Odrzuć|Zaproszenie wysłane|Oczekujące zaproszenia",
  "ja": "グループ|グループはまだありません|グループを作って、大切な人たちと共有しましょう。|メンバー%d人|新しいグループ|グループ名|Momentsでメンバーを選びましょう。2人以上を招待して、最大50人のグループを作成できます。|%d人選択済み|ユーザーが見つかりません。|メンバーを招待|ユーザーを検索|グループの詳細|メッセージはエンドツーエンドで暗号化されます。招待を承認した人はグループの履歴を読むことができます。|以前のメッセージ|返信|写真|メッセージ|キャンセル|送信|保存|通知をミュート|メンバー|所有者|管理者|管理者にする|管理者権限を削除|メンバーを削除|メンバーを管理|グループを退出|グループにアクセスできなくなります。所有者の場合は、別のメンバーにその役割が引き継がれます。|この人はグループにアクセスできなくなります。ダウンロード済みのメッセージを相手の端末から削除することはできません。|操作を完了できませんでした|OK|戻る|グループを読み込めませんでした。戻って再試行してください。|このグループにはアクセスできません。|チャットの鍵が利用できません。メンバーはチャットの鍵を設定または復元する必要があります。|送信できませんでした。下書きは残っています。再試行してください。|この写真を読み込めませんでした。|グループを更新できませんでした。接続と権限を確認して再試行してください。|%@さんがメッセージを送信しました|グループへの招待|承認|辞退|招待を送信しました|承認待ちの招待",
  "ko": "그룹|아직 그룹이 없어요|그룹을 만들어 소중한 사람들과 나눠 보세요.|멤버 %d명|새 그룹|그룹 이름|Moments에서 사람을 선택하세요. 최소 2명을 초대하여 최대 50명의 그룹을 만들 수 있습니다.|%d명 선택됨|검색된 사람이 없습니다.|사람 초대|사람 검색|그룹 정보|메시지는 종단 간 암호화됩니다. 초대를 수락한 사람은 그룹의 이전 대화를 읽을 수 있습니다.|이전 메시지|답장|사진|메시지|취소|보내기|저장|알림 끄기|멤버|소유자|관리자|관리자로 지정|관리자 권한 해제|멤버 내보내기|멤버 관리|그룹 나가기|그룹에 더 이상 접근할 수 없게 됩니다. 소유자라면 다른 멤버가 역할을 이어받습니다.|이 사람은 그룹에 더 이상 접근할 수 없게 됩니다. 이미 다운로드한 메시지는 상대방 기기에서 지울 수 없어요.|작업을 완료하지 못했어요|확인|뒤로|그룹을 불러오지 못했어요. 뒤로 가서 다시 시도하세요.|이 그룹에 더 이상 접근할 수 없어요.|채팅 키를 사용할 수 없어요. 멤버가 채팅 키를 설정하거나 복원해야 합니다.|보내지 못했어요. 초안은 남아 있으니 다시 시도하세요.|이 사진을 불러오지 못했어요.|그룹을 업데이트하지 못했어요. 연결과 권한을 확인한 뒤 다시 시도하세요.|%@님이 메시지를 보냈어요|그룹 초대|수락|거절|초대를 보냈습니다|대기 중인 초대",
  "zh-Hant": "群組|還沒有群組|建立群組，與在乎的人分享。|%d 位成員|新增群組|群組名稱|在 Moments 選擇成員。邀請至少 2 人，即可建立最多 50 人的群組。|已選擇 %d 人|找不到使用者。|邀請成員|搜尋使用者|群組資訊|訊息採用端對端加密。接受邀請的人可以閱讀群組的聊天記錄。|較早的訊息|回覆|照片|訊息|取消|傳送|儲存|靜音通知|成員|擁有者|管理員|設為管理員|移除管理員身分|移除成員|管理成員|離開群組|你將無法存取群組。如果你是擁有者，將由其他成員接任。|此人將無法存取群組。已下載的訊息無法從對方裝置刪除。|無法完成操作|確定|返回|無法載入群組。請返回並重試。|你已無法存取此群組。|無法使用聊天金鑰。成員需要設定或還原聊天金鑰。|無法傳送。草稿仍在，請再試一次。|無法載入這張照片。|無法更新群組。請檢查連線與權限後重試。|%@ 傳送了一則訊息|群組邀請|接受|拒絕|已傳送邀請|待處理的邀請",
  "hi": "समूह|अभी कोई समूह नहीं है|अपनों के साथ साझा करने के लिए समूह बनाएँ।|%d सदस्य|नया समूह|समूह का नाम|Moments पर लोगों को चुनें। अधिकतम 50 सदस्यों वाला समूह बनाने के लिए कम से कम 2 लोगों को आमंत्रित करें।|%d चुने गए|कोई व्यक्ति नहीं मिला।|लोगों को आमंत्रित करें|लोगों को खोजें|समूह की जानकारी|संदेश एंड-टू-एंड एन्क्रिप्टेड हैं। आमंत्रण स्वीकार करने वाले लोग समूह का पुराना चैट इतिहास पढ़ सकते हैं।|पुराने संदेश|जवाब दें|फ़ोटो|संदेश|रद्द करें|भेजें|सहेजें|सूचनाएँ म्यूट करें|सदस्य|स्वामी|एडमिन|एडमिन बनाएँ|एडमिन की भूमिका हटाएँ|सदस्य हटाएँ|सदस्य प्रबंधित करें|समूह छोड़ें|आप समूह का ऐक्सेस खो देंगे। अगर आप स्वामी हैं, तो कोई दूसरा सदस्य यह भूमिका संभालेगा।|यह व्यक्ति समूह का ऐक्सेस खो देगा। पहले से डाउनलोड किए गए संदेश उसके डिवाइस से नहीं मिटाए जा सकते।|कार्रवाई पूरी नहीं हो सकी|ठीक है|वापस|समूह लोड नहीं हो सका। वापस जाकर फिर कोशिश करें।|अब आपके पास इस समूह का ऐक्सेस नहीं है।|चैट की कुंजियाँ उपलब्ध नहीं हैं। सदस्यों को अपनी चैट कुंजियाँ सेट अप या बहाल करनी होंगी।|भेजा नहीं जा सका। आपका ड्राफ़्ट यहीं है; फिर कोशिश करें।|यह फ़ोटो लोड नहीं हो सकी।|समूह अपडेट नहीं हो सका। कनेक्शन और अनुमतियाँ जाँचकर फिर कोशिश करें।|%@ ने संदेश भेजा|समूह आमंत्रण|स्वीकार करें|अस्वीकार करें|आमंत्रण भेजा गया|लंबित आमंत्रण",
  "id": "Grup|Belum ada grup|Buat grup untuk berbagi dengan orang-orang terdekat.|%d anggota|Grup baru|Nama grup|Pilih orang di Moments. Undang setidaknya 2 orang untuk membuat grup dengan maksimal 50 anggota.|%d dipilih|Tidak ada orang ditemukan.|Undang orang|Cari orang|Detail grup|Pesan dienkripsi secara end-to-end. Orang yang menerima undangan dapat membaca riwayat grup.|Pesan sebelumnya|Balas|Foto|Pesan|Batal|Kirim|Simpan|Bisukan notifikasi|Anggota|Pemilik|Admin|Jadikan admin|Hapus peran admin|Keluarkan anggota|Kelola anggota|Keluar dari grup|Kamu akan kehilangan akses ke grup. Jika kamu pemiliknya, peran itu akan dialihkan ke anggota lain.|Orang ini akan kehilangan akses ke grup. Pesan yang sudah diunduh tidak dapat dihapus dari perangkatnya.|Tindakan tidak dapat diselesaikan|OK|Kembali|Grup tidak dapat dimuat. Kembali dan coba lagi.|Kamu tidak lagi memiliki akses ke grup ini.|Kunci chat tidak tersedia. Anggota perlu menyiapkan atau memulihkan kunci chat mereka.|Tidak dapat mengirim. Drafmu masih ada; coba lagi.|Foto ini tidak dapat dimuat.|Grup tidak dapat diperbarui. Periksa koneksi dan izinmu, lalu coba lagi.|%@ mengirim pesan|Undangan grup|Terima|Tolak|Undangan terkirim|Undangan tertunda",
  "tr": "Gruplar|Henüz grubun yok|Sevdiklerinle paylaşmak için bir grup oluştur.|%d üye|Yeni grup|Grup adı|Moments’taki kişileri seç. En fazla 50 üyeli bir grup oluşturmak için en az 2 kişiyi davet et.|%d seçildi|Kişi bulunamadı.|Kişileri davet et|Kişi ara|Grup ayrıntıları|Mesajlar uçtan uca şifrelenir. Daveti kabul edenler grubun geçmişini okuyabilir.|Önceki mesajlar|Yanıtla|Fotoğraf|Mesaj|İptal|Gönder|Kaydet|Bildirimleri sessize al|Üyeler|Sahip|Yönetici|Yönetici yap|Yönetici rolünü kaldır|Üyeyi çıkar|Üyeyi yönet|Gruptan ayrıl|Gruba erişimini kaybedeceksin. Grubun sahibiysen bu rol başka bir üyeye geçer.|Bu kişi gruba erişimini kaybedecek. Önceden indirilen mesajlar cihazından silinemez.|İşlem tamamlanamadı|Tamam|Geri|Grup yüklenemedi. Geri dönüp tekrar dene.|Artık bu gruba erişimin yok.|Sohbet anahtarları kullanılamıyor. Üyelerin sohbet anahtarlarını ayarlaması veya geri yüklemesi gerekiyor.|Gönderilemedi. Taslağın hâlâ burada; tekrar dene.|Bu fotoğraf yüklenemedi.|Grup güncellenemedi. Bağlantını ve izinlerini kontrol edip tekrar dene.|%@ bir mesaj gönderdi|Grup davetleri|Kabul et|Reddet|Davet gönderildi|Bekleyen davetler"
}
qual={'en':'values','pt-BR':'values-b+pt+BR','pt-PT':'values-b+pt+PT','zh-Hant':'values-b+zh+Hant','id':'values-in'}
def resource(k): return 'groups_' + re.sub(r'([A-Z])', lambda m:'_'+m[1].lower(),k)
for lang,row in translations.items():
    values=row.split('|')
    if len(values)!=len(keys): raise ValueError((lang,len(values),len(keys)))
    entries=dict(zip(keys,values))
    ios=(ROOT / 'Moments/Moments')/(lang+'.lproj')/'Localizable.strings'
    current=ios.read_text()
    # Idempotent insertion for this feature only.
    current=re.sub(r'\n// Group chat\n(?:"groups\.[^\n]+\n)+', '\n', current)
    ios.write_text(current.rstrip()+'\n\n// Group chat\n'+''.join('"groups.'+k+'" = '+json.dumps(v,ensure_ascii=False)+';\n' for k,v in entries.items()))
    android=(ROOT / 'MomentsAndroid/app/src/main/res')/qual.get(lang,'values-'+lang)/'strings_groups.xml'
    def esc(v): return html.escape(v.replace('%d','%1$d').replace('%@','%1$s'),quote=False).replace("'", "\\'").replace('"','\\"')
    android.write_text('<?xml version="1.0" encoding="utf-8"?>\n<resources>\n'+''.join('    <string name="'+resource(k)+'">'+esc(v)+'</string>\n' for k,v in entries.items())+'</resources>\n')
p=(ROOT / 'MomentsAndroid/app/src/main/java/com/moments/android/views/messaging/groups/GroupStrings.kt')
p.write_text('package com.moments.android.views.messaging.groups\n\nimport com.moments.android.R\n\ninternal fun groupStringId(key: String): Int = when (key) {\n'+''.join('    "'+k+'" -> R.string.'+resource(k)+'\n' for k in keys)+'    else -> R.string.groups_error\n}\n')
p=(ROOT / 'MomentsAndroid/app/src/main/java/com/moments/android/views/messaging/groups/GroupChatViews.kt');s=p.read_text()
for k in keys: s=s.replace('R.string.groups_'+k,'R.string.'+resource(k))
p.write_text(s)
print('Written', len(keys),'strings in',len(translations),'locales for both apps.')
